#!/bin/bash

#it works only if use simlinks
#not works with alias
#for alias user instead zxset

D=$(dirname $0)
. $D/zxconf
O=$(basename $0)
. zxset "$O" "$*"
#CO="#0 $*"
#echo $CO
#grep -v "$O " $ZXPROG>$ZXPROG.tmp
#cp $ZXPROG $ZXPROG.bak
#echo $CO >>$ZXPROG.tmp
#cat $ZXPROG.tmp|sort -h>$ZXPROG
#rm $ZXPROG.tmp
#echo ZX Ok


